### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by KintCark** [ShiftHackZ/Local-Diffusion-Models-SDAI-MediaPipe#1]
Can I contribute I made some mediapipe models also can I upload them here? How would I do it?

I got one here and more on my storage;)

MANOFAi94/Lexica-Art-3.5-Mediapipe-Format

**Comment by ShiftHackZ** [comment]
Hi, any contribution is appreciated and welcomed. 

To contribute, please upload them to google drive / mega / another public storage, and publish links here.

Here are the requirements for the models:
- each model should be packaged as .zip file, and have the same structure as already published models;
- model file should not be larger that 2 Gb.

In case you converted the model by yourself, please also publish link to the model source.

Thanks!

**Comment by KintCark** [comment]
> Hi, any contribution is appreciated and welcomed. 
> 
> To contribute, please upload them to google drive / mega / another public storage, and publish links here.
> 
> Here are the requirements for the models:
> - each model should be packaged as .zip file, and have the same structure as already published models;
> - model file should not be larger that 2 Gb.
> 
> In case you converted the model by yourself, please also publish link to the model source.
> 
> Thanks!

Hey how do I post. Link? Do I need to post link to model source in a txt file? I need push access?

**Comment by KintCark** [comment]
> Hi, any contribution is appreciated and welcomed. 
> 
> To contribute, please upload them to google drive / mega / another public storage, and publish links here.
> 
> Here are the requirements for the models:
> - each model should be packaged as .zip file, and have the same structure as already published models;
> - model file should not be larger that 2 Gb.
> 
> In case you converted the model by yourself, please also publish link to the model source.
> 
> Thanks!

I made a fork but how do I merge it with yours?

https://github.com/KintCark/Local-Diffusion-Models-SDAI-MediaPipe

**Comment by ShiftHackZ** [comment]
Thanks for your contribution, model is now available in app live!

I could not merge your fork directly, because of 2 reasons:
- GitHub does not allow merge releases.
- I repackaged zip archive correctly (all files should be placed in root).
